template_path: templates/sg_wrapper.py

hooks:
  before_create:
    - !account_verifier {{ var.account_id }}
  before_update:
    - !account_verifier {{ var.account_id }}

stack_tags:
  seg-team: {{ var.team_name }}
  seg-app: {{ var.service_name }}
  seg-env: {{ var.environment }}

sceptre_user_data:
  VpcId: !stack_output_external sceptre-vpcinfra-common-vpc::VpcId
  SecurityGroups:
    - name: PublicSecurityGroup
      description: allow inbound traffic from internet on specified ports
      ingress_rules:
        - port: 80
          proto: tcp
          source_ip: {{ var.allowed_ingress_source_ip }}
        - port: 443
          proto: tcp
          source_ip: {{ var.allowed_ingress_source_ip }}
    - name: PrivateSecurityGroup
      description: allow inbound traffic from public security group on any port
      ingress_rules:
        - source_sg: PublicSecurityGroup

