template_path: templates/cf-origin-access-identity.yaml

hooks:
    before_create:
        - !account_verifier {{ var.poc_account_id }}
    before_update:
        - !account_verifier {{ var.poc_account_id }}

parameters:
  Comment:

stack_tags:
  team: devops
  app: cfs3sites
  env: poc
