---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Web Application Firewall allows access from a single trusted subnet.'

Parameters:
  TrustedSubnet:
    Description: 'CIDR address for trusted subnet'
    Type: String
    Default: '10.10.0.0/16'

Resources:
  IPSetTrustedSubnet: 
    Type: AWS::WAF::IPSet
    Properties: 
      Name: 'IPSet for trusted subnet'
      IPSetDescriptors: 
        - 
          Type: IPV4
          Value: 
            Ref: TrustedSubnet

  RuleTrustedSubnet: 
    Type: AWS::WAF::Rule
    Properties: 
      Name: TrustedSubnet
      MetricName: TrustedSubnet
      Predicates: 
        - 
          DataId: 
            Ref: IPSetTrustedSubnet
          Negated: true
          Type: IPMatch

  TrustedSubnetWebACL: 
    Type: AWS::WAF::WebACL
    Properties: 
      Name: TrustedSubnetWebACL
      DefaultAction: 
        Type: ALLOW
      MetricName: TrustedSubnetWebACL
      Rules: 
        - 
          Action: 
            Type: BLOCK
          Priority: 1
          RuleId: 
            Ref: RuleTrustedSubnet

Outputs:
  TrustedSubnetWebACL:
    Value:
      Ref: TrustedSubnetWebACL
    Description: 'Trusted subnet Web ACL allows access from trusted subnet only'
