template_path: templates/trusted-subnet-webacl.yaml

hooks:
    before_create:
        - !account_verifier {{ var.poc_account_id }}
    before_update:
        - !account_verifier {{ var.poc_account_id }}

parameters:
  TrustedSubnet: {{ var.on_prem_subnet }}

stack_tags:
  team: devops
  app: cfs3sites
  env: poc
