template_path: templates/cfs3site-log-bucket.py

hooks:
    before_create:
        - !account_verifier {{ var.poc_account_id }}
    before_update:
        - !account_verifier {{ var.poc_account_id }}


stack_tags:
  team: devops
  app: cfs3sites
  env: poc

sceptre_user_data: {}
