template_path: templates/vpc_wrapper.py

hooks:
  before_create:
    - !account_verifier {{ var.account_id }}
  before_update:
    - !account_verifier {{ var.account_id }}


stack_tags:
  seg-team: {{ var.team_name }}
  seg-app: {{ var.service_name }}
  seg-env: {{ var.environment }}


sceptre_user_data:
  VpcCIDR: 10.128.0.0/16
  AZCount: 2
