template_path: templates/bitbucketsync.yaml

hooks:
    before_create:
      - !account_verifier {{ var.account_id }}

    before_update:
      - !account_verifier {{ var.account_id }}

stack_tags:
  seg-team: {{ var.team_name }}
  seg-app: {{ var.service_name }}
  seg-env: {{ var.env }}

parameters:
  ProjectName: {{ var.service_name }}

