AWSTemplateFormatVersion: 2010-09-09
Description: |
      Create resources prerequisite to deploying Cloudfront S3 websites:
        a S3 bucket for logging access to Cloudfront origins,
        a Cloudfront S3 origin access identity,
        a Web Application Firewall allowing access from a single trusted subnet.

Parameters:
  TrustedSubnet:
    Description: CIDR address for trusted subnet
    Type: String
    Default: 10.10.0.0/16
  LogBucket:
    Description: Name of the s3 log bucket this template creates.
    Type: String
    #Default: cfs3site-logbucket
  Comment:
    Description: Comment to associate with the origin access identity.
    Type: String
    Default: Created by sceptre-project-cfs3site

Resources:

  CFS3SiteLogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogBucket
      AccessControl: LogDeliveryWrite

  CFS3SiteLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CFS3SiteLogBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Resource: !Sub 'arn:aws:s3:::${CFS3SiteLogBucket}/*'
            #Resource: !Join
            #  - ''
            #  - - arn:aws:s3:::
            #    - !Ref LogBucket
            #    - /*
            Sid: CFS3SiteLogBucketPolicy

  RuleTrustedSubnet: 
    Type: AWS::WAF::Rule
    Properties: 
      Name: TrustedSubnet
      MetricName: TrustedSubnet
      Predicates: 
        - 
          DataId: 
            Ref: IPSetTrustedSubnet
          Negated: true
          Type: IPMatch

  TrustedSubnetWebACL: 
    Type: AWS::WAF::WebACL
    Properties: 
      Name: TrustedSubnetWebACL
      DefaultAction: 
        Type: ALLOW
      MetricName: TrustedSubnetWebACL
      Rules: 
        - 
          Action: 
            Type: BLOCK
          Priority: 1
          RuleId: 
            Ref: RuleTrustedSubnet

  IPSetTrustedSubnet: 
    Type: AWS::WAF::IPSet
    Properties: 
      Name: IPSet for trusted subnet
      IPSetDescriptors: 
        - 
          Type: IPV4
          Value: 
            Ref: TrustedSubnet

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Ref: Comment

Outputs:
  CFS3SiteLogBucket:
    Description: Cloudfront S3 website log bucket
    Value: !Ref CFS3SiteLogBucket
  TrustedSubnetWebACL:
    Value:
      Ref: TrustedSubnetWebACL
    Description: Trusted subnet Web ACL allows access from trusted subnet only
  OriginAccessIdentity:
    Value:
      Ref: OriginAccessIdentity
    Description: Cloudfront origin access identity
  S3CanonicalUserId:
    Value:
      Fn::GetAtt: OriginAccessIdentity.S3CanonicalUserId
    Description: S3 canonical user ID for the origin access identity
