AWSTemplateFormatVersion: 2010-09-09
Description: Build project documentation with Sphinx and post to a Cloudfront S3 origin
  bucket.
Parameters:
  ProjectName:
    Type: String
    Description: Name of this project
  ProjectRepository:
    Type: String
    Description: Name of codecommit repo for project
  ProjectBranch:
    Type: String
    Description: The branch of the project repository this pipeline will monitor
    Default: master
  ProjectSphinxPath:
    Type: String
    Description: Path to sphinx directory relative to root of project repository
  CFOriginBucket:
    Type: String
    Description: Name of cloudfront s3 origin bucket we are populating.
  CodeBuildImage:
    Type: String
    Description: >
      Docker image to use for CodeBuild container
      CF http://amzn.to/2mjCI91 for reference
    Default: python:3.5.2
  BuildSpec:
    Type: String
    Description: Path to codebuild buildspec file relative to project base directory
    Default: aws/docbuilder/codebuild/buildspec-sphinxdocs.yaml



Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub PipelineExecutionRole-${ProjectName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codepipeline.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodePipelineS3ArtifactAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodePipelineS3ArtifactAccess
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${PipelineArtifactsBucket}'
                  - !Sub 'arn:aws:s3:::${PipelineArtifactsBucket}/*'
              - Sid: CodePipelineGitRepoAccess
                Effect: Allow
                Action:
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive
                Resource: '*'
              - Sid: CodePipelineBuildAccess
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:BatchGetBuilds
                Resource:
                  - !GetAtt CodeBuildSphinxDocs.Arn
              - Sid: CodePipelinePassRoleAccess
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CodeBuildServiceRole.Arn

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildServiceRole-${ProjectName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild2S3
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub 'arn:aws:s3:::${PipelineArtifactsBucket}'
                  - !Sub 'arn:aws:s3:::${PipelineArtifactsBucket}/*'
                  - !Sub 'arn:aws:s3:::${CFOriginBucket}'
                  - !Sub 'arn:aws:s3:::${CFOriginBucket}/*'
              - Sid: CodeBuild2CloudWatch
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  CodeBuildSphinxDocs:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub BuildSphinxDocs-${ProjectName}
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Sub aws/codebuild/${CodeBuildImage}
        EnvironmentVariables:
          - Name: ORIGIN_BUCKET
            Value: !Ref CFOriginBucket
          - Name: SPHINX_PATH
            Value: !Ref ProjectSphinxPath
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpec
      TimeoutInMinutes: 15

  DocBuilderPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub DocBuilderPipeline-${ProjectName}
      RoleArn: !GetAtt PipelineExecutionRole.Arn
      ArtifactStore:
        Location: !Ref PipelineArtifactsBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: ProjectSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                BranchName: !Ref ProjectBranch
                RepositoryName: !Ref ProjectRepository
              OutputArtifacts:
                - Name: ProjectSource
        - Name: BuildDocs
          Actions:
            - Name: BuildSphinxDocs
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: ProjectSource
              Configuration:
                ProjectName: !Ref CodeBuildSphinxDocs
              RunOrder: '1'

Outputs:
  PipelineArtifactsBucket:
    Description: CodePipeline Artifacts S3 Bucket
    Value: !Ref PipelineArtifactsBucket
  DocBuilderPipeline:
    Description: Sphinx docs builder CodePipeline
    Value: !Ref DocBuilderPipeline
