AWSTemplateFormatVersion: 2010-09-09
Description: 'Create a Cloudfront S3 origin access identity.'

Parameters:
  Comment:
    Description: 'Comment to associate with the origin access identity.'
    Type: String
    Default: 'Created by sceptre-project-cfs3site'

Resources:
  OriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Ref: Comment
          
Outputs:
  OriginAccessIdentity:
    Value:
      Ref: OriginAccessIdentity
    Description: 'Cloudfront origin access identity'
  S3CanonicalUserId:
    Value:
      Fn::GetAtt: OriginAccessIdentity.S3CanonicalUserId
    Description: 'S3 canonical user ID for the origin access identity'
