template_path: templates/vpc_flowlogs_wrapper.py

stack_tags:
  team: engineering
  app: sceptremods
  env: example

sceptre_user_data:
  VpcId: !stack_output example/vpc::VpcId
  Tags:
    stackermods_version: !package_version sceptremods

